[package]
name = "rudy"
version = "0.0.1"
authors = ["anurse <andrew@andrewnurse.net>"]

[dependencies]
sdl2 = "0.4.0"
log = "0.3.1"
env_logger = "0.3.1"

[dependencies.remy]
version = "0.0.1"
path = "../remy"
